### ISSUE TITLE
Array leak? 

### ISSUE THREAD

**Issue by TheExDeus** [enigma-dev/enigma-dev#930]
It seems we have some kind of array problem when using with(){} statement.
Check out this example: https://portal.emakonis.lv/Shares/Home.aspx?ShareID=11d45c04-3161-4198-ba46-034631c8ec8a

If you run it in normal mode the game will either crash or will show a message printing out the arrays (inputs[] and outputs[]) instead of the numbers asked. This leads me to believe that somehow the variables are highjacked by the arrays.
It works fine if you comment out the with(){} part in obj_controller and uncomment the part in obj_node.

Also, it works fine in debug mode. Which is even weirder, which leads me to believe this is a memory issue.

I don't know if it's somehow connected to the array changes by sorlok.

**Comment by sorlok** [comment]
What compiler are you using? Just FYI, I've experienced the whole "it works fine in debug mode, crashes with -O2 (or -O3)" on several occasions, and adding "-g" to the optimized build does not lead to any particularly troubling-looking code. If memory is getting corrupted, then I really have no clue where.

The example you provided is pretty small, though, so I'll try running it through clang and valgrind to see if anything shows up.

**Comment by TheExDeus** [comment]
mingw32 coming with ENIGMA.

**Comment by sorlok** [comment]
It will likely still crash with -g; that's just for a better backtrace. 

Could you find out which version of gcc+mingw? I am using 4.8.2, for reference, and it is possible this is actually a bug in gcc, not enigma. 

I haven't had time to try your example yet; I'll likely get to it on the weekend.

**Comment by TheExDeus** [comment]
I have 4.8.2.
Here is the backtrace: http://pastebin.com/21mxauT2
It seems the object accessors are generated incorrectly. It seems actually that array problem is just a side effect. In reality the error happens even if I comment the arrays out.
Basically what I do is create an empty object (which doesn't have any of the variables defined):
I then launch a script that defines two variable - "input_count = 0" and "output_count = 0"
Then I launch two scripts that increment these variables - "input_count++" and "output_count++"
And I launch the final script that draws these variables in a show_message().
All of this is done inside a with(){} statement, because as I said I don't create these variables inside the object.


I reduced the example to basically 10 lines of code.

**Comment by sorlok** [comment]
Excellent! That will definitely help me track stuff down. If we're lucky, this will just be a gcc bug; the fact that we're both using 4.8.2 is a good sign in this direction.

**Comment by TheExDeus** [comment]
I don't think the fact that it is a GCC bug is good thing, because then we can't really fix it. I'm hoping it's a 5 line parser fix.

**Comment by sorlok** [comment]
Are you sure that this is the same bug? The latest script you sent (with w/h) crashes with both -O0 and -O3, but the original bug only crashed on -O0 (I think). 

Anyway, this is definitely a bug and needs to be fixed in the parser. I'm fairly sure I know what's causing it; fixing it might be a little trickier.

**Comment by sorlok** [comment]
Here's the crux of the problem:

# We mark variables in the "collect_variables()" function, which is part of the parser (so it doesn't have access to things like the list of objects, etc).
# We don't really track "with()" scopes that much; every place that I know of re-calculates the "with()" scope level as it goes. This is partly because the code and synt strings are constantly being resized (which would make updating an external index really painful). 
# When "with(obj_1)" is encountered, the collect_variables() function has no way of retrieving the parsed_event* associated with object 1 (it might not have even been created yet).

This is somewhat systemic; it might be easier to clean up some of the data flow in the compiler first. For example, if we built a symbol table as we went along, then code and synt could be constant, and we could at least identify the proper with() scope.

**Comment by sorlok** [comment]
Sorry for the spam, but there's actually another issue here. Even if we tagged "obj_1" correctly, we'd still have the issue of "with(some_var)". But there's *another* issue; my test code tags "obj_1" as a local variable in obj_0 (leading to an infinite loop). This must be some recent breakage; I'll need to track that down first.

**Comment by TheExDeus** [comment]
Any progress here? For now I develop my stuff in debug mode, but at some point I would want to run it at full optimization. I haven't found a painless way around this, as it fails even if I define all variables beforehand.

**Comment by sorlok** [comment]
Sorry, I've been a bit busy and haven't tried anything yet.

**Comment by sorlok** [comment]
I'm having trouble opening your example in the latest version of ENIGMA, with the following error:
http://pastie.org/9860198

Has LGM changed in a non-backwards-compatible way recently?

**Comment by RobertBColton** [comment]
@sorlok When I added the multiple constants/configs the EGM format clearly broke. I simply don't have the time right now to sit down and fix it. Theoretically it should be fixed LGM side by making constants/configs an instantiable resource instead of ArrayList as I wrote them. Maybe I'll try to sit down and fix it soon.

**Comment by TheExDeus** [comment]
Yeah, EGM is broke in newest version. That is why I don't use the newest version.
Try this gmk instead: https://portal.emakonis.lv/Shares/Home.aspx?ShareID=9fd160a7-2674-4946-98b3-a522ce57acde

**Comment by sorlok** [comment]
Oh, thanks, I'll try that.

**Comment by sorlok** [comment]
Some more information on the problem:
* gcc-4.7 is fine
* gcc-4.8 has the bug
* gcc-4.9 has the bug
* clang does *not* have the bug.

This at least helps Linux users; I wonder how reasonable it would be to use clang on Windows? 

I'm still not sure if this is a gcc bug or an ENIGMA bug, or something in between (i.e., we generate really weird code that gcc chokes on).

**Comment by TheExDeus** [comment]
That's interesting. If it does turn out to be gcc bug, then it will have to be reported. I don't know if using on clang is an option. I haven't ever tried it, but I have been interested in it, as it usually gives a very optimized output. Clang had a different license, but I don't think it hurts us.

**Comment by TheExDeus** [comment]
Have you made any progress on this? If it's a GCC bug then we should report it. While I was looking at the outputted code it did look a little fishy to me, so for now I still think it's our parser. I can try looking into clang for windows.

**Comment by sorlok** [comment]
Sorry no progress. I think it's a combination of us outputting weird code, and gcc choking on it. But at the moment I'm not sure how to narrow down either side (us vs. gcc) any further.

**Comment by JoshDreamland** [comment]
Harri, can you please paste the codegen for the faulty access, with the name of the thing that isn't accessed right? I don't know what would cause the behavior to differ between GCC versions. I eyed this bug a couple times looking for any info that can be obtained without trying to run a big example, but no one's posted anything concrete yet except that EGM, which would require me to run the EGM, see what it's doing, figure out what it should be doing, *then* diagnose the problem.

To clarify, there's not much we can do about the problems coercing variables in `with()`... or to be precise, there are a lot of things we can do to cover various cases in mostly efficient ways, but nothing we can do to cover all the cases in a nice way. We can try to evaluate at compile time the object index being passed to `with()`, but `with (choose(obj0, obj1, obj2))` is completely valid. We can generate getters and setters for dynamic scripts to use, but that's basically what we're already doing, and the current infrastructure isn't good enough to do much better.

**Comment by TheExDeus** [comment]
That EGM consists of 6 lines of code. This is the code with added 7th line.
```var inst = instance_create(10,10,obj_1); 
with (inst){
 w = 10;
 h = 20; 
 scr_somescript(w,h); 
}

//scr_somescript()
show_message(string(w)+" "+string(h));```

It should create an instance obj_1, assign local variables w and h for the instance (the variables are NOT declared in obj_1 create event or anywhere else) and show them.
I have found that there is different behavior with different make flags. I have modified my makefile by removing -fno-exceptions and then I get an empty message box. If I add the "-fno-exceptions" back, then it segfaults. And it segfaults even if I remove show_message() (so it calls an empty script like the EGM posted).
Here is the objectfunctionality: http://pastebin.com/2DxxXqgc
And objectaccess: http://pastebin.com/3Y9McuDv

I think this line: enigma::varaccess_w(int(self))= 10; is wrong, because it tries to get _w for obj_1 (as it's inside the with (obj_1) block), but no varaccess is made for that. Instead there is varaccess for _w in obj_0, which actually doesn't define w or h. So it defaults to:```default: return map_var(&(((enigma::object_locals*)inst)->vmap), "w");``` which somehow segfaults.

**Comment by JoshDreamland** [comment]
Everything you said is the intended behavior until "which somehow segfaults." Looking at the local codegen, it seems that vmap is correctly initialized, so I'm going to have to run it locally. Glad I know what it is I'm looking for, though. My only preliminary thought is that `map_var` is coded in an inefficient and somewhat insecure way, but it shouldn't matter since there are no threads. I'll get back to you in a tick.

**Comment by JoshDreamland** [comment]
This is very peculiar. It's the first Heisenbug I've seen in quite a while. My guess is that it's a problem in the GCC optimizing compiler. I am able to reproduce this bug using only two empty objects and the following code in the create event of the first:

```C++
int inst = instance_create(10, 10, obj_1); 
with (inst) {
  yes1 = 10;
  yes2 = 20;
}
```
The map access function *should* look like [this](http://pastebin.com/tqwtK8xa). Even if it looks like this, though, the problem persists:

```C++
  var vd;
  var &map_var(std::map<string, var> **vmap, string str) {
      return vd;
  }
```

Which means that the issue is not in the map or how we handle it. I considered that it may be a glitch in the implementation of `var`. Before I got into that, I decided to print just a little more debug information...

Normally the var access looks like this:
```C++
  var  &varaccess_yes1(int x)
  {
    object_basic *inst = fetch_instance_by_int(x);
    if (inst) switch (inst->object_index)
    {
      case obj_0: return ((OBJ_obj_0*)inst)->yes1;
      case global: return ((ENIGMA_global_structure*)ENIGMA_global_instance)->yes1;
      default: return map_var(&(((enigma::object_locals*)inst)->vmap), "yes1");
    }
    return dummy_0;
  }
```

Beneath the first line, I added `printf("OBJECT INDEX: %d (x=%d)\n", inst->object_index, x);`, in order to print the input object index (should be self, -1) and the resulting object index. In the second, identical call, I added the same line with a "2" after the object. The result was fascinating:
```
OBJECT INDEX: 1 (x=-1)
OBJECT INDEX: 0 (x=-1)
```

"Curious; something must have invalidated the iterator or overwritten the object index" was what I was thinking. To be sure, I decided to add a second iterator lookup immediately after the first, so that the code now read as follows:
```C++
    object_basic *inst = fetch_instance_by_int(x);
    printf("OBJECT INDEX: %d (x=%d)\n", inst->object_index, x);
    inst = fetch_instance_by_int(x);
    printf("OBJECT! INDEX: %d (x=%d)\n", inst->object_index, x);
```

The output was now as follows:
```
OBJECT INDEX: 1 (x=-1)
OBJECT! INDEX: 1 (x=-1)
OBJECT2 INDEX: 0 (x=-1)
```
This suggested that the problem was occurring in the map operation afterward... except that I had already cleared it of all assign logic. So something must be happening between the two calls. To be sure, I duplicated the assignment code (`yes1 = 10`) three times, then did the same for the `yes2` assignment. This effect the following output:
```
OBJECT INDEX: 1 (x=-1)
OBJECT! INDEX: 1 (x=-1)
OBJECT INDEX: 1 (x=-1)
OBJECT! INDEX: 1 (x=-1)
OBJECT INDEX: 1 (x=-1)
OBJECT! INDEX: 1 (x=-1)
OBJECT2 INDEX: 1 (x=-1)
OBJECT2 INDEX: 0 (x=-1)
OBJECT2 INDEX: 0 (x=-1)
```

We now successfully execute one of the `yes2` assignments. Okay. So I added debug code to it as well:
```C++
    object_basic *inst = fetch_instance_by_int(x);
    printf("OBJECT2 INDEX: %d (x=%d)\n", inst->object_index, x);
    inst = fetch_instance_by_int(x);
    printf("OBJECT2! INDEX: %d (x=%d)\n", inst->object_index, x);
```

The issue vanished:
```
OBJECT INDEX: 1 (x=-1)
OBJECT! INDEX: 1 (x=-1)
OBJECT INDEX: 1 (x=-1)
OBJECT! INDEX: 1 (x=-1)
OBJECT INDEX: 1 (x=-1)
OBJECT! INDEX: 1 (x=-1)
OBJECT2 INDEX: 1 (x=-1)
OBJECT2! INDEX: 1 (x=-1)
OBJECT2 INDEX: 1 (x=-1)
OBJECT2! INDEX: 1 (x=-1)
OBJECT2 INDEX: 1 (x=-1)
OBJECT2! INDEX: 1 (x=-1)
```

No segfault, no nothing. The problem was gone without a trace. I decided to inspect whether the correct `map_var` was being called. Removing the secondary print statements from the accessor functions, I discovered that even so much as incrementing my `vd` variable before returning a reference to it would cause the problem to vanish.

Replacing `var` with `int` has no effect, nor does disabling all extensions. The error, of course, never rears its ugly head with debugging symbols included.

I'm relatively certain this is a GCC bug. The best course of action is to narrow a test case and file a bug against GCC. I'll do that after some sleep.

**Comment by sorlok** [comment]
Wow, nice sleuthing. This is a really weird bug.

**Comment by TheExDeus** [comment]
Thanks for tracking that down. I hope we can get this fixed.

**Comment by TheExDeus** [comment]
I still have this bug you know... One way to fix it is to just rewrite the code differently, like having the object id before every variable. That worked for a while, but now it segfaults there too. I have tried a lot of different things, but it just comes and disappears all the time. I have GCC 4.9.2 now, same problem.

**Comment by JoshDreamland** [comment]
I never managed to get the test case small enough to warrant submitting a compiler bug. It certainly didn't help that a lot of ENIGMA's systems can no longer be disabled (or replaced with dummies). It only took me a few hours of trying to just cut out the tiny bit of the instance system we actually need to test this before I gave up out of boredom. Trying to track the bug down manually was much more interesting. Looking at the problem again, you could probably fix it by taking a reference to the dummy variable at any point in the code (which would force it into memory and make the problem disappear).

**Comment by TheExDeus** [comment]
But is this really a GCC bug? If so then it should really be reported. It seemed you got quite a lot smaller test case there.

Right now I just do ugly stuff like instead of "with (some_id) { a = 0; b = 10; c= 10;}" I write "some_id.a=0; some_id.b=10; some_id.c=10;". For a longer script this is extremely ugly, but the only fix  I can think of.

**Comment by JoshDreamland** [comment]
The code I have to change to demonstrate something funky is happening is small. The amount of code that has to be included to *build* this is *enormous*. No GCC developer wants to dig through thousands of lines of code when only a handful are involved. And whether other code in ENIGMA is actually what's causing this bug can't be fully established until I've narrowed a test case. For example, if there were other threads in ENIGMA trying to access variables, this bug would be fully explained outside of GCC. I just don't know of (and can't find) any threading.

**Comment by TheExDeus** [comment]
There is no threading in ENIGMA systems, even though when you run it in gdb it often prints that a thread has exited as some points. Originally I thought it was because of OpenAL which might use a thread inside, but the same sometimes happens without OpenAL included too. So that is weird, but could be unrelated, because ENIGMA systems doesn't have any threading.

**Comment by sorlok** [comment]
A good workaround is to compile with -O0 instead of -O2. That's what I do for my Ludum Dare entries.

**Comment by TheExDeus** [comment]
There are plenty of workarounds - you can just compile in debug mode if you want. But none of them are good, because compiling "production code" without optimization is kind of useless. A better fix is to actually fix it.

**Comment by JoshDreamland** [comment]
I invite you to direct your determination at creating a minimal test case. My enthusiasm for doing so was gone a few hours into the operation. Make a local copy of the code base. Start by disabling all extensions and all systems (sound, networking, collisions) and compiling in ENIGMA. From there, cut out as many headers as you possibly can. After that, it's a matter of removing as many lines of code from the headers as you can. The preprocessor can't help you, because it wants to embed the entire STL contents in the output if you ask it to preprocess. Maybe you're patient enough to deal with that? I wasn't. So basically, any headers you can't cut out, you have to manually paste in (but only the first occurrence, so don't make my mistake and keep a list). After an hour or so of removing chunks of code, you'll be to a point where you can start inlining code to remove more, maybe. I didn't get that far, because cutting out just the bits of the instance system I needed was painful, and revealed the volume of code I'd have to pick through manually, which was overwhelming.

You're welcome, of course, to try filing a bug without doing this, but it'll never be accepted. Whatever you choose, good luck.

**Comment by TheExDeus** [comment]
I'll see what I can do. I have to finalize some other things I'm working on in ENIGMA. I'll probably make a quick post about them as I promised that a few weeks ago.
I was hoping a little more involvement from you, but I guess ENIGMA hasn't interested you in years now. Could the parser you never finished maybe fix this issue? I don't know if it generates the variable access code differently or not.

**Comment by JoshDreamland** [comment]
That new parser would allow for a new variable access mechanism, but I hadn't made any specific plans to implement one. I've always wanted to find an elegant solution for optimizing accesses, but never came up with anything really inspirational. And no, boiling down a little test case from our huge codebase doesn't interest me. I'll still nibble on interesting problems, though, if you have any.

**Comment by RobertBColton** [comment]
Universal System has threading that I wrote for the GM Studio compatible async dialogs. I have no idea if I knew what I was doing when I wrote it or if it automatically launches threads. Why can't you just run a process analysis tool on the game and see what threads are running?

**Comment by RobertBColton** [comment]
@JoshDreamland and @TheExDeus Great news! It looks like this was fixed. Because the EGM format has changed I had to recreate his minimal example:

obj_0 create event
```gml
var inst = instance_create(10,10,obj_1); 
with (inst){
 w = 10;
 h = 20; 
 scr_somescript(w,h); 
}
```

Then add an obj_1 and scr_somescript that do nothing. Then place an instance of obj_0 in a room and run. No errors in run mode or debug mode. It would be nice to see the original example/game that was crashing to see if it still is.

Anyway, this may have been fixed when Josh had to fix the other crashes caused by instance iterators inside with statements. @JoshDreamland just fixed this about a week ago.
https://github.com/enigma-dev/enigma-dev/pull/999

@TheExDeus should test from his branch and then apply Josh's fix in #999 to see if it does in fact correct the issue. I will try to revert #999 somehow on my end and see if it breaks again.

**Comment by RobertBColton** [comment]
Ok I managed to create a branch and do this:
``$ git revert -m 1 5ef6525d767c4d6ffbc0731738d028428804665c``

This reverts #999 by Josh. When I revert it my recreation of Harri's with example begins crashing again. But on current master, my recreation of it does not crash. So I am pretty sure this was fixed by #999 unless someone else wants to test further.

**Comment by RobertBColton** [comment]
Also I just realized that his minimal example calls a script inside with() which is exactly why Josh made #999 to fix #983. Removing the script call makes it stop crashing with Josh's fix reverted.

So I am pretty certain this can be closed as resolved.

**Comment by JoshDreamland** [comment]
To be honest, as soon as you pointed out the stack smashing, I assumed that my fix would also correct this bug. The problem was, when I was investigating, Valgrind was completely unable to locate any kind of stack smashing or memory corruption, in spite of the fact that this is the simplest example of it. It's as bad as returning a reference to a local, or `string.c_str()` where `string` is a local. I have no idea why Valgrind was unable to locate what was happening. Regardless, I'm not surprised that my fix closed the book on this.

**Comment by RobertBColton** [comment]
Oh and I also forgot that he had ``show_message(string(w)+" "+string(h));`` inside that script. I added that to my recreation and it does in fact work on master and show "10 20"
